version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - setup_remote_docker
      - run: npm install

      - deploy:
          name: push docker images
          command: |
            [ "${CIRCLE_BRANCH}" != "master" ] && [ -z "${CIRCLE_TAG}" ] && exit 0

            export DOCKER_REPO=$(echo "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" | awk '{print tolower($0)}')

            docker login -u ${DOCKER_USER} -p "${DOCKER_PASS}" https://index.docker.io/v1/
            docker build -t ${DOCKER_REPO} .

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push ${DOCKER_REPO}
            fi

            if [ -n "${CIRCLE_TAG}" ]; then
              docker tag ${DOCKER_REPO} ${DOCKER_REPO}:${CIRCLE_TAG}
              docker push ${DOCKER_REPO}:${CIRCLE_TAG}
            fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: docker
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
